# Dependencies
highlighter:      pygments
gems: [jekyll-paginate, jekyll-gist]

kramdown:
  input: GFM

# Permalinks
permalink:        pretty

# Setup
title:            'Alex Pawlowski'
tagline:          'At the intersection of mobility and additive manufacturing'
description:      'Triathlete. PhD Student at the University of Tennessee focusing in Transportation Science.'
baseurl:          /
location:         'Knoxville, TN'

author:
  name:           '@AlexPawlowski_'
  url:            https://twitter.com/AlexPawlowski_

paginate:         5

# Custom vars
version:          1.0.3

github:
  repo:           https://github.com/alexpawlowski
