# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            'Alex Pawlowski'
tagline:          'Melding E-Waste with Plant Waste'
description:      'Triathlete. Graduate Student at the University of Tennessee working towards a PhD in Energy Science and Engineering focusing in Transportation Science.'
baseurl:          /

author:
  name:           '@AlexPawlowski_'
  url:            https://twitter.com/AlexPawlowski_

paginate:         5

# Custom vars
version:          1.0

github:
  repo:           https://github.com/alexpawlowski
