# Dependencies
plugins:
  - github-pages

highlighter: rouge

markdown: kramdown

include:  ["_pages"]

# Permalinks
permalink:        /:title/

# Setup
title:            'Alex Pawlowski'
tagline:          'At the intersection of mobility and additive manufacturing'
description:      'Triathlete. PhD student at Tennessee applying additive mfg in transportation materials'
baseurl:          /
location:         'Knoxville, TN'
_author:
  name:           '@AlexPawlowski_'
  url:            https://twitter.com/AlexPawlowski_

paginate:         5
excerpt-separator: <!--more-->

collections:
  projects:
      output: true
      permalink: /projects/:path/
  races:
      output: true

# Custom vars
version:          1.2.0

github:
  repo:           https://github.com/alexpawlowski

accounts:
  - github: alexpawlowski
  - twitter: apawlows
  - linkedin: alexpawlowski
  - google_scholar: MLhGOi4AAAAJ
