# Dependencies
highlighter:      rouge
gems: [jekyll-paginate, jekyll-gist]

kramdown:
  input: GFM

include:  ["_pages"]

# Permalinks
permalink:        /:title/

# Setup
title:            'Alex Pawlowski'
tagline:          'At the intersection of mobility and additive manufacturing'
description:      'Triathlete. PhD Student at Tennessee focusing in Transportation Science.'
baseurl:          /
location:         'Knoxville, TN'

author:
  name:           '@AlexPawlowski_'
  url:            https://twitter.com/AlexPawlowski_

paginate:         5

collections:
  projects:
      output: true
      permalink: /projects/:path/
  races:
      output: true

# Custom vars
version:          1.1.0

github:
  repo:           https://github.com/alexpawlowski
